17 the aep tree creation
HeinzLabPurdue/NEL pull request #18
Opened 2022-08-01 20:25 UTC by HeinzLabPurdue

VMA and SH corrected the AEP tree so that ABR and CAP work under the general naming scheme of AEP. 
EcochG, RW and ABR are all confirmed to be working with the new file structure. 
FFR still will run, and will be 2 chan as JMR irrespective of the user. 
FFR organization to be continued, but general folder set up is ready. 
Everything in this pull request is functional for data collection.

2022-09-02 15:02 UTC, sivaprakasaman requested changes
dB SPL not printing in window in ABR protocol under AEP. Also no "auto levels" seems to have been replaced by an "Audiogram" button. Needs to be fixed before PR...will check if this is an issue on master as well

2023-06-27 17:45 UTC, hausersn1 commented
Fixed the following issues: dB SPL not printing in window in ABR protocol under AEP. Also no "auto levels" seems to have been replaced by an "Audiogram" button. 

Also changed: Added CAP calib file application as it is in ABR. Previously was just all pass

2023-06-27 17:53 UTC, sivaprakasaman approved these changes

2023-06-27 17:57 UTC, hausersn1 approved these changes

2023-06-27 18:12 UTC, merged