52 fpl calibration implementation
HeinzLabPurdue/NEL pull request #53
Opened 2023-09-01 17:25 UTC by HeinzLabPurdue

SH confirmed ABR/FFR/FPL functionality on both NEL1 and NEL2. Ready to merge w/ master

2023-10-19 16:04 UTC, sivaprakasaman requested changes
ProbeCal_Data must be untracked & git ignored

2023-10-22 20:08 UTC, sivaprakasaman requested changes
Need to properly untrack and ignore probe calib files

2023-10-22 20:08 UTC, sivaprakasaman commented on Nel_matlab/FPL/Probe/ProbeCal_Data/FPLprobe_01-Sep-2023_1.mat
These are all still here...

Follow instructions [here](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files). It's also possible you need to untrack/retrack files in this current commit.

2023-10-22 20:24 UTC, hausersn1 commented on Nel_matlab/FPL/Probe/ProbeCal_Data/FPLprobe_01-Sep-2023_1.mat
Yeah, I know. This was me fiddling with it while doing something else. I think I figured out how to do it for real and will do this week (trying for Monday).

2023-10-24 20:55 UTC, hausersn1 commented
Okay, these should now be untracked. Whole folder looks gone to me.

2023-11-15 17:48 UTC, hausersn1 approved these changes
This branch has been working for many experiments. Approving changes. 

Could add things for ease of flow/error catching (i.e., cancel button for FPL ear/probe), but does work in current state. ProbeCal has been added to gitignore.

2023-11-15 17:52 UTC, sivaprakasaman approved these changes
Seems good. We've been testing this branch and it's worked. The daily probe calib files are now removed. 

I'm noticing hundreds of 'files changed' but most of the non-FPL ones should be those going into xArchive.

2023-11-15 17:55 UTC, merged